### ISSUE TITLE
Parent Profile Card/Account

### ISSUE THREAD

**Issue by Lunn99** [dong200k/Youth-Sports-Center#28]
Create UI so that parents can

- View their account information ( as seen in the User collection in the db schemas) as a card
- Edit their account information from the card that holds this information

**Comment by Lunn99** [comment]
#32

**Comment by dong200k** [comment]
![image](https://user-images.githubusercontent.com/81045036/165017439-66f9d49b-5d7d-442f-a5ad-10fdcf6b330e.png)

**Comment by dong200k** [comment]
![image](https://user-images.githubusercontent.com/81045036/165017464-18969622-b6fb-4119-904d-d9f1b27a8977.png)
