### ISSUE TITLE
Home Page Front End

### ISSUE THREAD

**Issue by dong200k** [dong200k/Youth-Sports-Center#7]
Create frontend for home page so that:

- Parents can view announcement
- Parent can interact with calendar to see classes for the day
- Parents can use navigation bar to navigate to different pages

**Comment by Lunn99** [comment]
![image](https://user-images.githubusercontent.com/71906158/160311331-dc00a0d5-e77c-48ec-b7e1-e17f1dacfe46.png)

**Comment by dong200k** [comment]
update:
![home](https://user-images.githubusercontent.com/81045036/165018565-0026ccfb-22ed-4f83-b8e2-067c10b857bf.gif)

**Comment by dong200k** [comment]
update:
![image](https://user-images.githubusercontent.com/81045036/165018629-c986ecff-b2b0-430f-b540-2db87fe487b7.png)
